#ifndef SPHERICALHARMONICS_HPP
#define SPHERICALHARMONICS_HPP

#include "types.hpp"

namespace vaspml::math
{

class SphericalHarmonics
{
  public:
    /// Data generated by integrate3SphericalHarmonics() function, contains results and lookup
    /// indices.
    struct Integrate3SphericalHarmonicsData
    {
        /// Maximum l possible with this data set.
        Int lmax;
        /// Integral of product of three spherical harmonics.
        Vec1Real ylm3;
        /// Inverse of integral of product of three spherical harmonics.
        Vec1Real ylm3i;
        /// Index @f$l_3@f$ corresponding to entries in ylm3.
        Vec1Int jl;
        /// Index combining @f$l_3@f$ and @f$m_3@f$ corresponding to entries in yml3 (js is computed
        /// as @f$l(l+1)+m+1@f$, where @f$m=-l,\ldots,l@f$.
        Vec1Int js;
        /// Index in ylm3 array corresponding to start position for one @f$l_1,l_2,m_1,m_2@f$
        /// combination.
        Vec1Int indcg;
        /// Index in indcg array corresponding to the start position for one @f$l_1,l_2@f$
        /// combination.
        Vec2Int lookup;
    };

    SphericalHarmonics(Int lmax);
    /** Computes real spherical harmonics and their derivatives for a set of normalized input
     * vectors up to a given maximum degree.
     *
     * This function requires a vector of normalized position vectors @f$\hat{\vec{r}}@f$
     * (@f$|\hat{\vec{r}}| = 1@f$) as input. The multi-dimensional data must be passed in a
     * flattened vector with this memory layout from fastest to slowest dimension:
     *   - Cartesian coordinate x, y, z (fastest)
     *   - Position vector index (slowest)
     *
     * The function computes @f$Y_{lm}@f$ up to @f$l = 4@f$ and then uses a recursion relation with
     * (some variant of) Clebsch-Gordan coefficients, i.e.,
     *
     * @f[
     * Y_{LM} = \sum_{ll'mm'} C_{ll'mm'}(L, M) Y_{lm} Y_{l'm'}.
     * @f]
     *
     * At the same time the corresponding derivatives with respect to the normalized input
     * coordinates @f$\frac{d Y_{lm}}{d \hat{x}_\alpha}@f$ are computed.
     *
     * The output vector `ylm` contains the spherical harmonics for all input vectors. The data is
     * passed as flattened vector with this memory layout:
     *   - Spherical harmonic order @f$m = -l,\ldots,0,\ldots,l@f$ (fastest)
     *   - Spherical harmonic degree @f$l = 0,\ldots,l_{\max}@f$
     *   - Position vector index (slowest)
     *
     * Similarly, the derivatives `ylmd` are provided in a flattened vector with this memory layout:
     *   - Cartesian coordinate of derivative @f$\alpha = 1, 2, 3@f$ (fastest)
     *   - Spherical harmonic order @f$m = -l,\ldots,0,\ldots,l@f$
     *   - Spherical harmonic degree @f$l = 0,\ldots,l_{\max}@f$
     *   - Position vector index (slowest)
     *
     * @param rhat Flattened array of normalized position vectors.
     * @param ylm Flattened array with real spherical harmonics up to maximum degree.
     * @param ylmd Flattened array with derivatives of real spherical harmonics.
     */
    void computeSphericalHarmonicsAndGradientsNormalized(const Vec1Real& rhat,
                                                         Vec1Real&       ylm,
                                                         Vec1Real&       ylmd) const;

    void computeSphericalHarmonicsAndGradientsNormalized(const Real* rhat,
                                                         const Size& nPoints,
                                                         Real*       ylm,
                                                         Real*       ylmd) const;
    /** Computes real spherical harmonics and their derivatives for a set of input vectors up to a
     * given maximum degree.
     *
     * This function requires a vector of normalized position vectors @f$\hat{\vec{r}}@f$
     * (@f$|\hat{\vec{r}}| = 1@f$) as input. The multi-dimensional data must be passed in a
     * flattened vector with this memory layout from fastest to slowest dimension:
     *   - Cartesian coordinate x, y, z (fastest)
     *   - Position vector index (slowest)
     *
     * In addition, the norms of all position vectors (@f$|\vec{r}|@f$) are required. The function
     * first computes @f$Y_{lm}@f$ up to @f$l = 4@f$ and then uses a recursion relation with (some
     * variant of) Clebsch-Gordan coefficients, i.e.,
     *
     * @f[
     * Y_{LM} = \sum_{ll'mm'} C_{ll'mm'}(L, M) Y_{lm} Y_{l'm'}.
     * @f]
     *
     * At the same time the corresponding derivatives with respect to the normalized input
     * coordinates @f$\frac{d Y_{lm}}{d \hat{x}_\alpha}@f$ are computed. This is done in the
     * function computeSphericalHarmonicsAndGradientsNormalized(). Finally, the identity
     *
     * @f[
     * \frac{d Y_{lm}}{d x_\alpha} = \sum_{\beta = 1}^{3} \frac{d Y_{lm}}{d \hat{x}_\beta}
     * \frac{1}{|\vec{r}|} \left( \delta_{\alpha\beta} - \hat{x}_\alpha \hat{x}_\beta \right)
     * @f]
     *
     * is used to determine the derivatives with respect to the unnormalized coordinates. The output
     * vector `ylm` contains the spherical harmonics for all input vectors. The data is passed as
     * flattened vector with this memory layout:
     *   - Spherical harmonic order @f$m = -l,\ldots,0,\ldots,l@f$ (fastest)
     *   - Spherical harmonic degree @f$l = 0,\ldots,l_{\max}@f$
     *   - Position vector index (slowest)
     *
     * Similarly, the derivatives `ylmd` are provided in a flattened vector with this memory layout:
     *   - Cartesian coordinate of derivative @f$\alpha = 1, 2, 3@f$ (fastest)
     *   - Spherical harmonic order @f$m = -l,\ldots,0,\ldots,l@f$
     *   - Spherical harmonic degree @f$l = 0,\ldots,l_{\max}@f$
     *   - Position vector index (slowest)
     *
     * @param rhat Flattened array of normalized position vectors.
     * @param rnorm Norms of input position vectors.
     * @param ylm Flattened array with real spherical harmonics up to maximum degree.
     * @param ylmd Flattened array with derivatives of real spherical harmonics.
     */
    void computeSphericalHarmonicsAndGradients(const Vec1Real& rhat,
                                               const Vec1Real& rnorm,
                                               Vec1Real&       ylm,
                                               Vec1Real&       ylmd) const;
    void computeSphericalHarmonicsAndGradients(const Real* rhat,
                                               const Real* rnorm,
                                               const Size& nPoints,
                                               Real*       ylm,
                                               Real*       ylmd) const;
    /** Computes one real spherical harmonic and derivatives for a given vector and l, m index pair.
     *
     * Similar to computeSphericalHarmonicsAndGradients(), but computes only one real spherical
     * harmonic @f$Y_{lm}@f$ corresponding to a single @f$l, m@f$-pair and one distance vector. The
     * distance vector must be provided as x,y,z-components of the normalized vector
     * @f$\hat{\vec{r}}@f$ (@f$|\hat{\vec{r}}| = 1@f$) and a separately provided norm
     * (@f$|\vec{r}|@f$).
     *
     * @warning Unlike computeSphericalHarmonicsAndGradients(), this function does not use a
     * recursive algorithm to compute spherical harmonics of higher order @f$l@f$. Hence, it can
     * only be use up to @f$l = 4@f$ for which hard-coded spherical harmonics are implemented.
     *
     * @param x x-component of normalized distance vector.
     * @param y y-component of normalized distance vector.
     * @param z z-component of normalized distance vector.
     * @param rnorm Norm of input distance vector.
     * @param l Spherical harmonic order @f$l@f$.
     * @param m Spherical harmonic degree @f$m@f$.
     * @param ylm Value of spherical harmonic.
     * @param ylmdx x-component of derivative of spherical harmonic.
     * @param ylmdy y-component of derivative of spherical harmonic.
     * @param ylmdz z-component of derivative of spherical harmonic.
     */
    void computeSphericalHarmonicAndGradient(const Real& x,
                                             const Real& y,
                                             const Real& z,
                                             const Real& rnorm,
                                             const Size& l,
                                             const Int&  m,
                                             Real&       ylm,
                                             Real&       ylmdx,
                                             Real&       ylmdy,
                                             Real&       ylmdz) const;
    /** Computes integral of product of three spherical harmonics.
     *
     * The integrated product of three spherical harmonics
     * @f[
     * \int_0^{2\pi} \int_0^\pi
     * Y_{l_1}^{m_1}(\vartheta, \phi)
     * Y_{l_2}^{m_2}(\vartheta,\phi)
     * Y_{l_3}^{m_3}(\vartheta,\phi)
     * \sin(\vartheta) d\vartheta d\phi =
     * \sqrt{\frac{(2l_1+1) (2l_2+1) (2l_3+1)}{4\pi}}
     * \left( \begin{array}{ccc} l_1 & l_2 & l_3 \\   0 &   0 &   0 \\ \end{array} \right)
     * \left( \begin{array}{ccc} l_1 & l_2 & l_3 \\ m_1 & m_2 & m_3 \\ \end{array} \right)
     * @f]
     * can be expressed in terms of a product of two Wigner 3j-symbols (which are related to the
     * Clebsch-Gordan coefficients, see clebschGordan() and clebschGordanM0()). It can be used to
     * recursively compute spherical harmonics. This function computes the integral up to a provided
     * maximum @f$l@f$ number for two spherical harmonics, e.g., @f$l_1, l_2@f$. The minimum and
     * maximum degree of the third spherical harmonic is assumed from the triangular condition
     * @f[
     * \left| l_1 - l_2 \right| \leq l_3 \leq l_1 + l_2
     * @f]
     *
     * @param lmax Maximum degree of the spherical harmonics integrated.
     * @param data Data container for results and lookup indices.
     */
    static void integrate3SphericalHarmonics(Int lmax, Integrate3SphericalHarmonicsData& data);
    Int         get_lmax() const;
    Int         get_ldim() const;
    Int         get_lhc() const;
    const Integrate3SphericalHarmonicsData& get_i3sh() const;

  private:
    /// Internal data required for computing spherical harmonics and derivatives.
    Integrate3SphericalHarmonicsData i3sh;
    /// Maximum l requested for this calculator.
    Int lmax;
    /// Total number of l, m combinations possible for given lmax in constructor.
    Int ldim;
    /// Maximum l for which spherical harmonics are hard coded.
    const Int lhc = 4;
};

} //namespace vaspml::math

#endif
